# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/00_config/00.00_cifar.ipynb.

# %% auto 0
__all__ = ["Config"]

# %% ../../nbs/00_config/00.00_cifar.ipynb 3
import json
from torch_snippets import *
from torch_snippets.trainer.config import DeepLearningConfig, GenericConfig

# %% ../../nbs/00_config/00.00_cifar.ipynb 4
class Config:
    """Update Me"""

    IMG_SIZE = 32  # input image size, CIFAR-10 is 32x32
    BATCH_SIZE = 128  # for training batch size
    timesteps = 16  # how many steps for a noisy image into clear
    time_bar = 1 - np.linspace(0, 1.0, timesteps + 1)  # linspace for timesteps
    device = torch.device("cuda") if torch.cuda.is_available() else torch.device("cpu")

    def to_json_string(self):
        o = {
            k: getattr(self, k)
            for k in dir(self)
            if ("__" not in k)
            and not any(k in d for d in ["time_bar", "to_json_string", "device"])
        }
        return json.dumps(o)
